In [4]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg


1. Vector Dot and Cross Products (10 pts) Define two vectors in
the plane: u = [2, 0], v = [3, 4]. Calculate their dot product by hand,
state the result in a markdown cell. Then create these two vectors as
numpy arrays and show that u@v gives the same result. Repeat the
calculation and numerical computation for the cross product

In [5]:
def dotProd(vecA, vecB):
    sum = 0
    for i, c in enumerate(vecA):
        sum+=vecA[i]*vecB[i]
    return sum

print(dotProd([2, 0], [3,4]))
print(np.dot(np.array([2, 0]), np.array([3, 4])))

6
6


In [6]:
def crossProd(vecA, vecB):
    temp = dotProd(vecA, vecB)
    vecASize = 0
    vecBSize = 0
    for i, c in enumerate(vecA):
        vecASize += vecA[i]**2
        vecBSize += vecB[i]**2
    vecASize = np.sqrt(vecASize)
    vecBSize = np.sqrt(vecBSize)
    temp = temp / (vecASize * vecBSize)
    theta = np.arccos(temp)
    return vecASize*vecBSize*np.sin(theta)

print(crossProd([2, 0], [3,4]))

8.0


2. Matrix multiplication (10 pts) Here are two matrices:
A =


1 3
2 4
5 6

 , B =
[ 2 1 4
3 2 1
]
Create these two matrices in Python, then print out A, B, and the
two matrix products A · B and B · A. (Hint: If you do something like
print(f’A =\n{aa}’) the matrix will print out nicely.) Calculate by
hand at least one element of A · B and one element of B · A and check
that these agree with your Python calculation

In [19]:
def matrixMultiply(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Cannot multiply")

    result = np.zeros((A.shape[0], B.shape[1]))


    for i in range(A.shape[0]):  
        for j in range(B.shape[1]):  
            for k in range(A.shape[1]):
                result[i][j] += A[i][k] * B[k][j]

    return np.array(result)

A = np.array([[1, 3], [2, 4], [5, 6]])
B = np.array([[2, 1, 4], [3, 2, 1]])

print(matrixMultiply(A, B))
print(matrixMultiply(B, A))

[[11.  7.  7.]
 [16. 10. 12.]
 [28. 17. 26.]]
[[24. 34.]
 [12. 23.]]


3. Inverse of a matrix (10 pts) Consider the matrix
C =


1 3 2
2 4 1
5 6 5
Have Python print out C, C−1, and C−1 · C. Is the last of these what
you expect?

In [8]:
def inverseOriginalAndProd(C):
    if np.shape(C)[0] != np.shape(C)[1]:
        print("No Inverse")
    else:
        print(C)
        print()
        print(linalg.inv(C))
        print()
        print(np.linalg.matmul(linalg.inv(C), C))

C = np.array([[1, 3, 2], [2, 4, 1], [5, 6, 5]])
inverseOriginalAndProd(C)

[[1 3 2]
 [2 4 1]
 [5 6 5]]

[[-0.82352941  0.17647059  0.29411765]
 [ 0.29411765  0.29411765 -0.17647059]
 [ 0.47058824 -0.52941176  0.11764706]]

[[ 1.00000000e+00  2.22044605e-16  2.22044605e-16]
 [-8.32667268e-17  1.00000000e+00 -8.32667268e-17]
 [ 2.22044605e-16  0.00000000e+00  1.00000000e+00]]


4. Solve a system of linear equations (10 pts) Use Python to solve
the following system of linear equations:
$$ x + 4y + z = −4, 
4x − y − z = 3, 
2x + y + 3z = 7.$$
for the three unknowns x, y and z. Do this two different ways: (a) by
multiplying the inverse of the matrix of coefficients by the RHS vector,
and (b) using linalg.solve (which is more accurate in general), and
check that both methods agree. Plug the solution for x, y, z into one
of the original equations to check that it is satisfied.

In [15]:
def equationSolver(*coeffs):
    # Convert tuples to a NumPy array
    augmented_matrix = np.array(coeffs, dtype=float)

    A = augmented_matrix[:, :-1]  
    b = augmented_matrix[:, -1]  
    try:
        x = np.linalg.solve(A, b)
        return x
    except np.linalg.LinAlgError as e:
        return f"Error: {e}"
    
def equationSolverByInv(*coeffs):
    augmented_matrix = np.array(coeffs, dtype=float)

    A = augmented_matrix[:, :-1]  
    b = augmented_matrix[:, -1]
    return(np.linalg.matmul(linalg.inv(A), b))
sol = equationSolver((1, 4, 1, -4), (4, -1, -1, 3), (2, 1, 3, 7))
print(sol)
print(1*sol[0]+4*sol[1]+1*sol[2])

sol1 = equationSolverByInv((1, 4, 1, -4), (4, -1, -1, 3), (2, 1, 3, 7))

print(sol1)
print(1*sol1[0]+4*sol1[1]+1*sol1[2])

[ 0.88461538 -1.80769231  2.34615385]
-4.000000000000001
[ 0.88461538 -1.80769231  2.34615385]
-4.000000000000001


6. Eigenvectors and eigenvalues of a real, symmetric matrix.(10
pts) Consider the following real, symmetric matrix
Sx =




0 √3/2 0 0√3/2 0 1 0
0 1 0 √3/2
0 0 √3/2 0



 .
(a) Compute and print out this matrix.
(b) Compute and print out the four eigenvectors and eigenvalues for
this matrix.
(c) Multiply the matrix by one of the eigenvectors and show that you
get what is expected.

In [ ]:
import numpy as np

def part6(S):
    print("Part A:\n", S)

    eigenvalues, eigenvectors = np.linalg.eig(S)

    print("\nPart B eigenVal:\n", eigenvalues)
    print("\nPart B eigenVec:\n", eigenvectors)

    Av = np.matmul(S, eigenvectors[:, 0])
    lambda_v = eigenvalues[0] * eigenvectors[:, 0]

    print(f"\nPart C: A·v = λ·v check for eigenvalue {eigenvalues[0]:.4f}")
    print("A·v =", Av)
    print("λ·v =", lambda_v)
    print("Difference:", Av - lambda_v)


S = np.array([
    [0, np.sqrt(3)/2, 0, 0],
    [np.sqrt(3)/2, 0, 1, 0],
    [0, 1, 0, np.sqrt(3)/2],
    [0, 0, np.sqrt(3)/2, 0]
])

part6(S)


Part A:
 [[0.        0.8660254 0.        0.       ]
 [0.8660254 0.        1.        0.       ]
 [0.        1.        0.        0.8660254]
 [0.        0.        0.8660254 0.       ]]

Part B eigenVal:
 [-1.5 -0.5  1.5  0.5]

Part B eigenVec:
 [[ 0.35355339  0.61237244 -0.35355339 -0.61237244]
 [-0.61237244 -0.35355339 -0.61237244 -0.35355339]
 [ 0.61237244 -0.35355339 -0.61237244  0.35355339]
 [-0.35355339  0.61237244 -0.35355339  0.61237244]]

Part C: A·v = λ·v check for eigenvalue -1.5000
A·v = [-0.53033009  0.91855865 -0.91855865  0.53033009]
λ·v = [-0.53033009  0.91855865 -0.91855865  0.53033009]
Difference (should be near zero): [-8.88178420e-16  1.22124533e-15 -8.88178420e-16  4.44089210e-16]
